//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAssignmentHistory
    {
        public int Id { get; set; }
        public string EcardID { get; set; }
        public string PlateNo { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
        public Nullable<System.DateTime> ReleasedAt { get; set; }
        public string Action { get; set; }
    }
}
