//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public string DocumentType { get; set; }
        public string EntityType { get; set; }
        public int EntityID { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileType { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
