//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcardReplenishmentRequest
    {
        public int Id { get; set; }
        public string EcardID { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> RequestedAmount { get; set; }
        public Nullable<decimal> BalanceAfter { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedAt { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    
        public virtual Ecard Ecard { get; set; }
    }
}
