//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ecard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ecard()
        {
            this.EcardReplenishmentRequests = new HashSet<EcardReplenishmentRequest>();
        }
    
        public string EcardID { get; set; }
        public string PlateNo { get; set; }
        public string CardType { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> ActivationDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcardReplenishmentRequest> EcardReplenishmentRequests { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
