//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelRefillRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FuelRefillRequest()
        {
            this.FuelTransactions = new HashSet<FuelTransaction>();
        }
    
        public int RequestID { get; set; }
        public string PlateNo { get; set; }
        public int DriverID { get; set; }
        public int CurrentOdometer { get; set; }
        public System.DateTime RequestDateTime { get; set; }
        public string ReceiptImage { get; set; }
        public string OdometerPhoto { get; set; }
        public string DigitalSignature { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> MileageDeviation { get; set; }
        public string ReviewStatus { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelTransaction> FuelTransactions { get; set; }
    }
}
