//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelStandard
    {
        public int StandardID { get; set; }
        public string VehicleType { get; set; }
        public int FuelTypeID { get; set; }
        public decimal StandardKmPerLiter { get; set; }
    
        public virtual FuelType FuelType { get; set; }
    }
}
