//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelTransaction
    {
        public int TransactionID { get; set; }
        public int RequestID { get; set; }
        public string PlateNo { get; set; }
        public int DriverID { get; set; }
        public decimal LitersUsed { get; set; }
        public decimal Amount { get; set; }
        public int BegKm { get; set; }
        public int EndKm { get; set; }
        public int D_KM { get; set; }
        public Nullable<decimal> AvgKmLiter { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public decimal EcardBalanceAfter { get; set; }
        public string Location { get; set; }
        public Nullable<int> ReceiptNum { get; set; }
        public string Product { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual FuelRefillRequest FuelRefillRequest { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
