//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Ecards = new HashSet<Ecard>();
            this.FuelRefillRequests = new HashSet<FuelRefillRequest>();
            this.FuelTransactions = new HashSet<FuelTransaction>();
        }
    
        public string PlateNo { get; set; }
        public string VehicleType { get; set; }
        public string ChassisNo { get; set; }
        public string MakeAndType { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CostCenterID { get; set; }
        public Nullable<int> VehicleAssignmentType { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int FuelTypeID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CostCenter CostCenter { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ecard> Ecards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelRefillRequest> FuelRefillRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuelTransaction> FuelTransactions { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual VehicleAssignmentType VehicleAssignmentType1 { get; set; }
    }
}
